sequenceDiagram
  participant participant_createAppStoreConnectDeploymentProvider as createAppStoreConnectDeploymentProvider
  participant participant_createAppStoreConnectIosPublisher as createAppStoreConnectIosPublisher
  participant participant_createAppStoreConnectMonetizationAdapter as createAppStoreConnectMonetizationAdapter
  participant participant_createAppStoreConnectReleaseAdapter as createAppStoreConnectReleaseAdapter
  participant participant_createAppStoreConnectRuntime as createAppStoreConnectRuntime
  participant participant_createAppStoreConnectSetupAdapter as createAppStoreConnectSetupAdapter
  participant participant_createAppStoreConnectStoreListingAdapter as createAppStoreConnectStoreListingAdapter
  participant_createAppStoreConnectDeploymentProvider->>participant_createAppStoreConnectRuntime: createAppStoreConnectRuntime()
  participant_createAppStoreConnectRuntime-->>participant_createAppStoreConnectDeploymentProvider: return
  participant_createAppStoreConnectDeploymentProvider->>participant_createAppStoreConnectSetupAdapter: createAppStoreConnectSetupAdapter()
  participant_createAppStoreConnectSetupAdapter-->>participant_createAppStoreConnectDeploymentProvider: return
  participant_createAppStoreConnectDeploymentProvider->>participant_createAppStoreConnectIosPublisher: createAppStoreConnectIosPublisher()
  participant_createAppStoreConnectIosPublisher-->>participant_createAppStoreConnectDeploymentProvider: return
  participant_createAppStoreConnectDeploymentProvider->>participant_createAppStoreConnectStoreListingAdapter: createAppStoreConnectStoreListingAdapter()
  participant_createAppStoreConnectStoreListingAdapter-->>participant_createAppStoreConnectDeploymentProvider: return
  participant_createAppStoreConnectDeploymentProvider->>participant_createAppStoreConnectMonetizationAdapter: createAppStoreConnectMonetizationAdapter()
  participant_createAppStoreConnectMonetizationAdapter-->>participant_createAppStoreConnectDeploymentProvider: return
  participant_createAppStoreConnectDeploymentProvider->>participant_createAppStoreConnectReleaseAdapter: createAppStoreConnectReleaseAdapter()
  participant_createAppStoreConnectReleaseAdapter-->>participant_createAppStoreConnectDeploymentProvider: return
